//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PromantusDBEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public System.Guid Id { get; set; }
        public string EmployeeID { get; set; }
        public string Employee1 { get; set; }
        public string GivenName { get; set; }
        public string SurName { get; set; }
        public decimal Mobile1 { get; set; }
        public Nullable<decimal> Mobile2 { get; set; }
        public System.DateTime DOB { get; set; }
        public System.DateTime DOJ { get; set; }
        public int GenderID { get; set; }
        public int PositionID { get; set; }
        public int DepartmentID { get; set; }
        public int CompanyID { get; set; }
        public string SkillSetIDs { get; set; }
        public System.Guid LocalAddressID { get; set; }
        public System.Guid PermanentAddressID { get; set; }
        public int EmployeeTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DeletedOn { get; set; }
        public System.Guid DeletedBy { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Address Address1 { get; set; }
        public virtual Company Company { get; set; }
        public virtual Department Department { get; set; }
        public virtual Position Position { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
